version: '3'

services:
  envoy:
    image: envoyproxy/envoy:v1.18.2
    volumes:
      - "./envoy.yml:/etc/envoy/envoy.yaml"
      - "./descriptors/proto.pb:/tmp/envoy/proto.pb"
    ports:
      - "${ENVOY_PORT}:${ENVOY_PORT}"