version: '3'

services:
  tracker:
    build: .
    ports:
      - "${TRACKER_SERVICE_PORT}:${TRACKER_SERVICE_PORT}"
  redis:
    image: redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"